import { Router } from "express";
import { getExploreFeed } from "../controllers/explore.controller";
import { getRecommendationsQuery } from "../controllers/recommendations.controller";
import { getContentCategories } from "../controllers/health.controller";
import { requireChild } from "../middlewares/rbac.middleware";
import { accountRouter } from "./account.routes";
import { analyticsRouter } from "./analytics.routes";
import { achievementRouter } from "./achievement.routes";
import { authRouter } from "./auth.routes";
import { chatRouter } from "./chat.routes";
import { messagesRestRouter } from "./messages.routes";
import { mediaRouter } from "./media.routes";
import { minorsRouter } from "./minors.routes";
import { contentRouter } from "./content.routes";
import { friendRouter } from "./friend.routes";
import { gameResultRouter } from "./gameResult.routes";
import { healthRouter } from "./health.routes";
import { parentRouter } from "./parent.routes";
import { postRouter } from "./post.routes";
import { quizRouter } from "./quiz.routes";
import { visualQuestionRouter } from "./visualQuestion.routes";
import { reactionRouter } from "./reaction.routes";
import { reportRouter } from "./report.routes";
import { userAchievementRouter } from "./userAchievement.routes";
import { userRouter } from "./user.routes";

export const apiRouter = Router();

apiRouter.get("/content-categories", getContentCategories);
apiRouter.get("/explore", requireChild, getExploreFeed);
apiRouter.get("/recommendations", requireChild, getRecommendationsQuery);
apiRouter.use("/analytics", analyticsRouter);
apiRouter.use("/health", healthRouter);
apiRouter.use("/account", accountRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/content", contentRouter);
apiRouter.use("/quiz", quizRouter);
apiRouter.use("/visual-quiz", visualQuestionRouter);
apiRouter.use("/achievements", achievementRouter);
apiRouter.use("/parents", parentRouter);
apiRouter.use("/friends", friendRouter);
apiRouter.use("/chat", chatRouter);
apiRouter.use(messagesRestRouter);
apiRouter.use("/media", mediaRouter);
apiRouter.use("/game-results", gameResultRouter);
apiRouter.use("/posts", postRouter);
apiRouter.use("/reports", reportRouter);
apiRouter.use("/reactions", reactionRouter);
apiRouter.use("/user-achievements", userAchievementRouter);
apiRouter.use("/users", userRouter);
apiRouter.use(minorsRouter);
