import { Router } from 'express';
import { getExploreFeed } from '../controllers/explore.controller';
import { getRecommendationsQuery } from '../controllers/recommendations.controller';
import { getContentCategories } from '../controllers/health.controller';
import { requireChild } from '../middlewares/rbac.middleware';
import { accountRouter } from './account.routes';
import { analyticsRouter } from './analytics.routes';
import { achievementRouter } from './achievement.routes';
import { authRouter } from './auth.routes';
import { chatRouter } from './chat.routes';
import { messagesRestRouter } from './messages.routes';
import { mediaRouter } from './media.routes';
import { missionsRouter } from './missions.routes';
import { minorsRouter } from './minors.routes';
import { adminRouter } from './admin.routes';
import { challengesRouter } from './challenges.routes';
import { assetsRouter } from './assets.routes';
import { educationalAssetRouter } from './educationalAsset.routes';
import { eventsRouter } from './events.routes';
import { gamificationRouter } from './gamification.routes';
import { gamesRouter } from './games.routes';
import { notificationsRouter } from './notifications.routes';
import { quizzesRouter } from './quizzes.routes';
import { socialRouter } from './social.routes';
import { contentRouter } from './content.routes';
import { friendRouter } from './friend.routes';
import { gameResultRouter } from './gameResult.routes';
import { healthRouter } from './health.routes';
import { parentRouter } from './parent.routes';
import { postRouter } from './post.routes';
import { quizRouter } from './quiz.routes';
import { visualQuestionRouter } from './visualQuestion.routes';
import { reactionRouter } from './reaction.routes';
import { reportRouter } from './report.routes';
import { userAchievementRouter } from './userAchievement.routes';
import { userRouter } from './user.routes';
import { coachRouter } from './coach.routes';
import { generousLimiter, mediumLimiter } from '../middlewares/rateLimit.middleware';

export const apiRouter = Router();

apiRouter.get('/content-categories', getContentCategories);
apiRouter.get('/explore', requireChild, getExploreFeed);
apiRouter.get('/recommendations', requireChild, getRecommendationsQuery);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/health', generousLimiter, healthRouter);
apiRouter.use('/account', accountRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/content', generousLimiter, contentRouter);
apiRouter.use('/educational-assets', generousLimiter, educationalAssetRouter);
apiRouter.use('/assets', generousLimiter, assetsRouter);
apiRouter.use('/quiz', quizRouter);
apiRouter.use('/visual-quiz', visualQuestionRouter);
apiRouter.use('/achievements', achievementRouter);
apiRouter.use('/parents', parentRouter);
apiRouter.use('/friends', friendRouter);
apiRouter.use('/chat', chatRouter);
apiRouter.use(messagesRestRouter);
apiRouter.use('/media', mediaRouter);
apiRouter.use('/game-results', gameResultRouter);
apiRouter.use('/posts', postRouter);
apiRouter.use('/reports', mediumLimiter, reportRouter);
apiRouter.use('/reactions', reactionRouter);
apiRouter.use('/user-achievements', userAchievementRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/coach', coachRouter);
apiRouter.use('/missions', generousLimiter, missionsRouter);
apiRouter.use('/challenges', mediumLimiter, challengesRouter);
apiRouter.use('/gamification', generousLimiter, gamificationRouter);
apiRouter.use('/quizzes', mediumLimiter, quizzesRouter);
apiRouter.use('/games', mediumLimiter, gamesRouter);
apiRouter.use('/social', mediumLimiter, socialRouter);
apiRouter.use('/events', generousLimiter, eventsRouter);
apiRouter.use('/notifications', mediumLimiter, notificationsRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use(minorsRouter);
