import type { EducationalContentItem, QuizQuestionItem } from "../types/api";
import { LEARN_MARKDOWN_BY_TOPIC_KEY } from "../data/learnBodies";

export type FallbackQuiz = {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  questionCount: number;
  topicId: string | null;
  published: boolean;
  questions: QuizQuestionItem[];
};

const createdAt = new Date(0).toISOString();

function question(
  id: string,
  category: string,
  difficulty: "EASY" | "MEDIUM" | "HARD",
  text: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  readingPassage?: string,
): QuizQuestionItem {
  return {
    id,
    question: text,
    options,
    correct: options.indexOf(correctAnswer),
    category,
    difficulty,
    createdAt,
    explanation,
    readingPassage: readingPassage ?? null,
    questionType: "MULTIPLE_CHOICE",
  };
}

const lunaPassage =
  "Era un día soleado y Luna estaba aburrida. No sabía qué hacer. De pronto, vio algo brillante entre las flores de su jardín. ¡Era un mapa antiguo! Luna siguió las pistas del mapa con la ayuda de su gato Milo. Cruzaron el jardín, pasaron por el árbol grande y llegaron al final del camino. Allí encontraron un cofre. Luna lo abrió con emoción. ¡Era un cofre lleno de libros antiguos sobre aventuras y magia! Luna aprendió que la verdadera aventura está en las historias que leemos.";

export const FALLBACK_QUIZZES: FallbackQuiz[] = [
  {
    id: "fallback-quiz-planetas",
    title: "🪐 Planetas del Sistema Solar",
    description: "Descubrí los secretos de nuestros vecinos espaciales",
    category: "astronomy",
    difficulty: "EASY",
    questionCount: 5,
    topicId: null,
    published: true,
    questions: [
      question(
        "fallback-planetas-1",
        "astronomy",
        "EASY",
        "¿Cuál es el planeta más grande del sistema solar?",
        ["Marte", "Júpiter", "Saturno", "Tierra"],
        "Júpiter",
        "🪐 ¡Júpiter es enorme! Cabrían 1.300 Tierras dentro de él. Tiene una mancha roja que es una tormenta gigante que dura siglos.",
      ),
      question(
        "fallback-planetas-2",
        "astronomy",
        "EASY",
        "¿Qué planeta es conocido como el 'planeta rojo'?",
        ["Venus", "Marte", "Mercurio", "Júpiter"],
        "Marte",
        "🔴 Marte es rojo porque su superficie tiene óxido de hierro (herrumbre). ¡Es como si estuviera oxidado!",
      ),
      question(
        "fallback-planetas-3",
        "astronomy",
        "EASY",
        "¿Cuántos planetas hay en el sistema solar?",
        ["7", "8", "9", "10"],
        "8",
        "🌌 Son 8: Mercurio, Venus, Tierra, Marte, Júpiter, Saturno, Urano y Neptuno. Plutón era el noveno pero ahora es 'planeta enano'.",
      ),
      question(
        "fallback-planetas-4",
        "astronomy",
        "EASY",
        "¿La Tierra gira alrededor de...?",
        ["La Luna", "Marte", "El Sol", "Júpiter"],
        "El Sol",
        "☀️ ¡Exacto! Un viaje completo alrededor del Sol dura 365 días. Eso es un año. El Sol es una estrella y está en el centro.",
      ),
      question(
        "fallback-planetas-5",
        "astronomy",
        "EASY",
        "¿Qué planeta tiene los anillos más famosos?",
        ["Júpiter", "Urano", "Saturno", "Neptuno"],
        "Saturno",
        "💫 Saturno tiene anillos enormes hechos de millones de pedacitos de hielo y roca. ¡Algunos pedazos son del tamaño de una casa!",
      ),
    ],
  },
  {
    id: "fallback-quiz-matematicas",
    title: "🔢 Sumas y Restas Divertidas",
    description: "Problemas cotidianos para calcular sin miedo",
    category: "math",
    difficulty: "EASY",
    questionCount: 5,
    topicId: null,
    published: true,
    questions: [
      question(
        "fallback-math-1",
        "math",
        "EASY",
        "Tenés 15 caramelos y tu mamá te da 7 más. ¿Cuántos tenés?",
        ["20", "21", "22", "23"],
        "22",
        "🍬 15 + 7 = 22. Truco: 15 + 5 = 20, y después 20 + 2 = 22. ¡Más caramelos para compartir!",
      ),
      question(
        "fallback-math-2",
        "math",
        "EASY",
        "Tenías 43 pesos y gastaste 18 en un juguete. ¿Cuánto te queda?",
        ["23", "24", "25", "26"],
        "25",
        "💰 43 - 18 = 25. Podés hacer: 43 - 10 = 33, y después 33 - 8 = 25. ¡Todavía te alcanza para un helado!",
      ),
      question(
        "fallback-math-3",
        "math",
        "EASY",
        "¿Cuánto es el doble de 12?",
        ["20", "22", "24", "26"],
        "24",
        "✌️ El doble es 12 + 12 = 24. O también: 10 + 10 = 20 y 2 + 2 = 4, entonces 20 + 4 = 24.",
      ),
      question(
        "fallback-math-4",
        "math",
        "EASY",
        "En la serie 2, 4, 6, 8, ... ¿qué número sigue?",
        ["9", "10", "11", "12"],
        "10",
        "🔢 ¡Son números pares! Van de 2 en 2: 2, 4, 6, 8, 10, 12... Después del 8 viene el 10.",
      ),
      question(
        "fallback-math-5",
        "math",
        "EASY",
        "Una caja tiene 4 filas de 5 chocolates cada una. ¿Cuántos hay?",
        ["15", "18", "20", "25"],
        "20",
        "🍫 4 × 5 = 20. También podés sumar: 5 + 5 + 5 + 5 = 20. ¡No te comas todos de una vez!",
      ),
    ],
  },
  {
    id: "fallback-quiz-materia",
    title: "🧪 Estados de la Materia",
    description: "Sólidos, líquidos, gases y experimentos simples",
    category: "science",
    difficulty: "EASY",
    questionCount: 5,
    topicId: null,
    published: true,
    questions: [
      question(
        "fallback-materia-1",
        "science",
        "EASY",
        "¿En qué estado está el agua cuando hierve?",
        ["Sólido", "Líquido", "Gas", "Plasma"],
        "Gas",
        "💨 Cuando hierve, el agua se convierte en vapor. El vapor es agua en estado gaseoso. ¡Cuidado con quemarte!",
      ),
      question(
        "fallback-materia-2",
        "science",
        "EASY",
        "¿El hielo es agua en estado...?",
        ["Líquido", "Sólido", "Gas", "Mixto"],
        "Sólido",
        "🧊 ¡Exacto! El hielo es agua congelada. Cuando se derrite, vuelve a ser líquida. Y si hierve, se hace gas.",
      ),
      question(
        "fallback-materia-3",
        "science",
        "EASY",
        "¿Qué necesita una planta para hacer fotosíntesis?",
        ["Solo agua", "Solo sol", "Sol, agua y aire", "Solo tierra"],
        "Sol, agua y aire",
        "🌱 Las plantas necesitan luz del sol, agua y dióxido de carbono (un gas del aire). Con eso hacen su alimento. ¡Son chefs naturales!",
      ),
      question(
        "fallback-materia-4",
        "science",
        "EASY",
        "¿Qué pasa si mezclas aceite y agua?",
        ["Se disuelven", "No se mezclan", "Se hacen espuma", "Cambian de color"],
        "No se mezclan",
        "🛢️ El aceite flota sobre el agua porque es menos denso. No se mezclan ni con mucha fuerza. ¡Probá en casa con un vaso!",
      ),
      question(
        "fallback-materia-5",
        "science",
        "EASY",
        "¿Cuál es el estado natural del oxígeno que respiramos?",
        ["Sólido", "Líquido", "Gas", "No tiene estado"],
        "Gas",
        "🌬️ El oxígeno es un gas invisible. Sin él no podríamos vivir. ¡Las plantas lo producen y nosotros lo respiramos!",
      ),
    ],
  },
  {
    id: "fallback-quiz-historia",
    title: "🏛️ Civilizaciones Antiguas",
    description: "Egipto, Roma y grandes momentos de la historia",
    category: "history",
    difficulty: "MEDIUM",
    questionCount: 5,
    topicId: null,
    published: true,
    questions: [
      question(
        "fallback-historia-1",
        "history",
        "MEDIUM",
        "¿Dónde vivían los faraones?",
        ["Roma", "Grecia", "Egipto", "China"],
        "Egipto",
        "👑 Los faraones eran los reyes del Antiguo Egipto. Construyeron las pirámides hace más de 3.000 años. ¡Algunas aún existen!",
      ),
      question(
        "fallback-historia-2",
        "history",
        "MEDIUM",
        "¿Qué construyeron los romanos para transportar agua?",
        ["Puentes", "Túneles", "Acueductos", "Canales"],
        "Acueductos",
        "🏗️ Los acueductos llevaban agua desde las montañas hasta las ciudades. Algunos romanos aún funcionan hoy en día. ¡Ingeniería increíble!",
      ),
      question(
        "fallback-historia-3",
        "history",
        "MEDIUM",
        "¿En qué año llegó Cristóbal Colón a América?",
        ["1490", "1492", "1500", "1510"],
        "1492",
        "⛵ El 12 de octubre de 1492. Pensaba que había llegado a la India, pero había descubierto un nuevo continente. ¡Un error histórico!",
      ),
      question(
        "fallback-historia-4",
        "history",
        "MEDIUM",
        "¿Qué inventaron los egipcios para escribir?",
        ["El alfabeto", "Los jeroglíficos", "La imprenta", "El papel"],
        "Los jeroglíficos",
        "𓀀 Los jeroglíficos eran dibujos que representaban palabras. Los escribían en papiros y paredes de templos. ¡Cada dibujo cuenta una historia!",
      ),
      question(
        "fallback-historia-5",
        "history",
        "MEDIUM",
        "¿Quién fue el primer presidente de Argentina?",
        ["San Martín", "Belgrano", "Bernardino Rivadavia", "Sarmiento"],
        "Bernardino Rivadavia",
        "🇦🇷 Fue presidente en 1826. San Martín y Belgrano fueron héroes de la independencia, pero no presidentes constitucionales.",
      ),
    ],
  },
  {
    id: "fallback-quiz-geografia",
    title: "🌍 Países y Capitales",
    description: "Capitales, continentes, ríos y mapas del mundo",
    category: "geography",
    difficulty: "EASY",
    questionCount: 5,
    topicId: null,
    published: true,
    questions: [
      question(
        "fallback-geo-1",
        "geography",
        "EASY",
        "¿Cuál es la capital de Francia?",
        ["Londres", "Madrid", "París", "Roma"],
        "París",
        "🗼 París es famosa por la Torre Eiffel. Allí también está el museo del Louvre, donde está la Mona Lisa.",
      ),
      question(
        "fallback-geo-2",
        "geography",
        "EASY",
        "¿En qué continente está Argentina?",
        ["Europa", "África", "Asia", "América del Sur"],
        "América del Sur",
        "🌎 Argentina está en el sur de Sudamérica. Limita con Chile, Bolivia, Paraguay, Brasil y Uruguay. ¡Y tiene la Patagonia!",
      ),
      question(
        "fallback-geo-3",
        "geography",
        "EASY",
        "¿Qué país tiene forma de bota?",
        ["España", "Grecia", "Italia", "Portugal"],
        "Italia",
        "👢 Italia parece una bota que 'patea' la isla de Sicilia. Es famosa por la pizza, la pasta y Roma.",
      ),
      question(
        "fallback-geo-4",
        "geography",
        "EASY",
        "¿Cuál es el río más largo del mundo?",
        ["Amazonas", "Nilo", "Misisipi", "Yangtsé"],
        "Nilo",
        "🌊 El Nilo en África mide unos 6.650 km. El Amazonas en Sudamérica es muy cercano. ¡Ambos son gigantes!",
      ),
      question(
        "fallback-geo-5",
        "geography",
        "EASY",
        "¿Cuántos continentes hay en el mundo?",
        ["5", "6", "7", "8"],
        "7",
        "🗺️ Son 7: África, Antártida, Asia, Europa, América del Norte, América del Sur y Oceanía. ¡Cada uno es un mundo diferente!",
      ),
    ],
  },
  {
    id: "fallback-quiz-arte",
    title: "🎨 Colores y Arte",
    description: "Mezclas, artistas famosos y colores del arcoíris",
    category: "creativity",
    difficulty: "EASY",
    questionCount: 5,
    topicId: null,
    published: true,
    questions: [
      question(
        "fallback-arte-1",
        "creativity",
        "EASY",
        "¿Cuáles son los colores primarios?",
        [
          "Rojo, verde, azul",
          "Rojo, azul, amarillo",
          "Naranja, verde, violeta",
          "Blanco, negro, gris",
        ],
        "Rojo, azul, amarillo",
        "🎨 Rojo, azul y amarillo. Con ellos podés mezclar para obtener otros colores. ¡Son la base de todo!",
      ),
      question(
        "fallback-arte-2",
        "creativity",
        "EASY",
        "¿Qué color se forma al mezclar azul y amarillo?",
        ["Naranja", "Violeta", "Verde", "Marrón"],
        "Verde",
        "💚 ¡Verde! Probá mezclar pinturas azul y amarilla en casa. También se ve en la naturaleza: cielo azul + sol amarillo = plantas verdes.",
      ),
      question(
        "fallback-arte-3",
        "creativity",
        "EASY",
        "¿Quién pintó la Mona Lisa?",
        ["Miguel Ángel", "Leonardo da Vinci", "Van Gogh", "Picasso"],
        "Leonardo da Vinci",
        "🖼️ Leonardo da Vinci la pintó alrededor de 1503. Está en el museo del Louvre en París. ¡Su sonrisa es un misterio!",
      ),
      question(
        "fallback-arte-4",
        "creativity",
        "EASY",
        "¿Qué artista mexicana se pintaba con monos en sus cuadros?",
        ["Diego Rivera", "Frida Kahlo", "Tamara de Lempicka", "Remedios Varo"],
        "Frida Kahlo",
        "🐒 Frida Kahlo era una pintora mexicana famosa por sus autorretratos. Los monos eran sus mascotas y aparecían en sus cuadros.",
      ),
      question(
        "fallback-arte-5",
        "creativity",
        "EASY",
        "¿Cuántos colores tiene el arcoíris?",
        ["5", "6", "7", "8"],
        "7",
        "🌈 7 colores: rojo, naranja, amarillo, verde, azul, añil y violeta. Se forma cuando la luz del sol pasa por gotas de agua. ¡Mágico!",
      ),
    ],
  },
  {
    id: "fallback-quiz-dinos",
    title: "🦕 Dinosaurios",
    description: "Nombres, fósiles y curiosidades prehistóricas",
    category: "science",
    difficulty: "EASY",
    questionCount: 5,
    topicId: null,
    published: true,
    questions: [
      question(
        "fallback-dino-1",
        "science",
        "EASY",
        "¿Qué significa 'dinosaurio'?",
        ["Reptil gigante", "Lagarto terrible", "Animal antiguo", "Bestia prehistórica"],
        "Lagarto terrible",
        "🦖 Viene del griego: 'deinos' (terrible) + 'sauros' (lagarto). No son lagartos, pero así los llamaron cuando los descubrieron.",
      ),
      question(
        "fallback-dino-2",
        "science",
        "EASY",
        "¿Qué dinosaurio tenía un cuello muy largo?",
        ["Tiranosaurio", "Velociraptor", "Braquiosaurio", "Triceratops"],
        "Braquiosaurio",
        "🦕 Medía 25 metros, ¡como un edificio de 8 pisos! Su cuello largo le servía para comer hojas de árboles altos.",
      ),
      question(
        "fallback-dino-3",
        "science",
        "EASY",
        "¿Qué dinosaurio era carnívoro con dientes enormes?",
        ["Braquiosaurio", "Diplodocus", "Tiranosaurio Rex", "Estegosaurio"],
        "Tiranosaurio Rex",
        "🦷 El T-Rex tenía dientes de hasta 30 cm. Su nombre significa 'rey de los lagartos tiranos'. ¡Era el depredador supremo!",
      ),
      question(
        "fallback-dino-4",
        "science",
        "EASY",
        "¿Qué causó la extinción de los dinosaurios?",
        ["Una inundación", "Un terremoto", "Un meteorito", "Un volcán"],
        "Un meteorito",
        "☄️ Hace 66 millones de años, un meteorito gigante chocó contra la Tierra. El polvo tapó el sol y cambió el clima. ¡Adiós, dinosaurios!",
      ),
      question(
        "fallback-dino-5",
        "science",
        "EASY",
        "¿Qué dinosaurio tenía placas en su espalda?",
        ["Tiranosaurio", "Velociraptor", "Estegosaurio", "Pteranodon"],
        "Estegosaurio",
        "🔺 Tenía placas óseas en la espalda y púas en la cola. Las placas servían para regular su temperatura o impresionar a otros.",
      ),
    ],
  },
  {
    id: "fallback-quiz-logica",
    title: "🧠 Lógica y Acertijos",
    description: "Trampas de lenguaje, series y deducciones",
    category: "puzzle",
    difficulty: "MEDIUM",
    questionCount: 5,
    topicId: null,
    published: true,
    questions: [
      question(
        "fallback-logica-1",
        "puzzle",
        "MEDIUM",
        "Si todos los gatos tienen cola y Mimi es un gato, entonces...",
        ["Mimi no tiene cola", "Mimi tiene cola", "Mimi es un perro", "No se puede saber"],
        "Mimi tiene cola",
        "🐱 ¡Lógica! Si TODOS los gatos tienen cola, y Mimi es gato → Mimi tiene cola. Es una deducción directa.",
      ),
      question(
        "fallback-logica-2",
        "puzzle",
        "MEDIUM",
        "En una familia hay 2 padres y 2 hijos. ¿Cuántas personas son como mínimo?",
        ["2", "3", "4", "5"],
        "3",
        "👨‍👩‍👦 Pueden ser 3: abuelo (padre), su hijo (padre e hijo), y el nieto (hijo). ¡El hijo es padre e hijo al mismo tiempo!",
      ),
      question(
        "fallback-logica-3",
        "puzzle",
        "MEDIUM",
        "¿Qué número sigue? 1, 1, 2, 3, 5, 8, ...",
        ["10", "11", "13", "15"],
        "13",
        "🔢 Serie de Fibonacci: cada número es la suma de los dos anteriores. 5 + 8 = 13. ¡Aparece en la naturaleza todo el tiempo!",
      ),
      question(
        "fallback-logica-4",
        "puzzle",
        "MEDIUM",
        "Un tren eléctrico va de norte a sur. ¿Hacia dónde va el humo?",
        ["Norte", "Sur", "Este", "Ninguno"],
        "Ninguno",
        "🚃 ¡Trampa! Es un tren ELÉCTRICO, no produce humo. Hay que leer bien antes de responder. ¡La lectura atenta es clave!",
      ),
      question(
        "fallback-logica-5",
        "puzzle",
        "MEDIUM",
        "Tengo 3 manzanas y VOS me sacás 2. ¿Cuántas tenés VOS?",
        ["1", "2", "3", "5"],
        "2",
        "🍎 Si VOS me sacás 2, VOS tenés 2. La pregunta es cuántas tenés VOS, no cuántas me quedan a mí. ¡Trampa de lenguaje!",
      ),
    ],
  },
  {
    id: "fallback-quiz-musica",
    title: "🎵 Música e Instrumentos",
    description: "Notas, piano, violín y familias musicales",
    category: "creativity",
    difficulty: "EASY",
    questionCount: 5,
    topicId: null,
    published: true,
    questions: [
      question(
        "fallback-musica-1",
        "creativity",
        "EASY",
        "¿Cuántas notas musicales básicas hay?",
        ["5", "6", "7", "8"],
        "7",
        "🎵 Do, re, mi, fa, sol, la, si. Con estas 7 notas se componen todas las melodías del mundo. ¡Solo 7!",
      ),
      question(
        "fallback-musica-2",
        "creativity",
        "EASY",
        "¿Qué instrumento tiene teclas blancas y negras?",
        ["Guitarra", "Violín", "Piano", "Flauta"],
        "Piano",
        "🎹 Tiene 88 teclas. Es uno de los instrumentos más populares. ¡Tocar piano ejercita ambos hemisferios del cerebro!",
      ),
      question(
        "fallback-musica-3",
        "creativity",
        "EASY",
        "¿Qué instrumento se toca con arco?",
        ["Piano", "Guitarra", "Violín", "Trompeta"],
        "Violín",
        "🎻 Se frotan las cuerdas con un arco. Tiene 4 cuerdas y es el más pequeño de su familia. ¡Suena hermoso!",
      ),
      question(
        "fallback-musica-4",
        "creativity",
        "EASY",
        "¿Qué familia de instrumentos usa aire para sonar?",
        ["Cuerda", "Percusión", "Viento", "Teclado"],
        "Viento",
        "🎺 Flauta, trompeta, saxofón... El músico sopla aire dentro. ¡Es como darle vida al instrumento con tu aliento!",
      ),
      question(
        "fallback-musica-5",
        "creativity",
        "EASY",
        "¿Quién compuso 'Las Cuatro Estaciones'?",
        ["Mozart", "Beethoven", "Vivaldi", "Bach"],
        "Vivaldi",
        "🍂 Antonio Vivaldi, alrededor de 1720. Describe musicalmente primavera, verano, otoño e invierno. ¡Escuchala!",
      ),
    ],
  },
  {
    id: "fallback-quiz-luna",
    title: "📖 Comprensión Lectora: La Aventura de Luna",
    description: "Leé una historia breve y respondé con atención",
    category: "education",
    difficulty: "EASY",
    questionCount: 5,
    topicId: null,
    published: true,
    questions: [
      question(
        "fallback-luna-1",
        "education",
        "EASY",
        "¿Dónde encontró Luna el mapa?",
        ["En la escuela", "En su jardín", "En la playa", "En el bosque"],
        "En su jardín",
        "📖 El texto dice: '...vio algo brillante entre las flores de su jardín. ¡Era un mapa antiguo!'",
        lunaPassage,
      ),
      question(
        "fallback-luna-2",
        "education",
        "EASY",
        "¿Qué animal la ayudó?",
        ["Un perro", "Un gato", "Un pájaro", "Un conejo"],
        "Un gato",
        "📖 El texto dice: '...con la ayuda de su gato Milo'. Milo es el nombre del gato.",
        lunaPassage,
      ),
      question(
        "fallback-luna-3",
        "education",
        "EASY",
        "¿Qué había en el cofre?",
        ["Monedas de oro", "Un cofre con libros", "Una caja de juguetes", "Una carta misteriosa"],
        "Un cofre con libros",
        "📖 El texto dice: '...un cofre lleno de libros antiguos sobre aventuras y magia'.",
        lunaPassage,
      ),
      question(
        "fallback-luna-4",
        "education",
        "EASY",
        "¿Qué aprendió Luna?",
        [
          "Que el tesoro era oro",
          "Que leer es una aventura",
          "Que los gatos hablan",
          "Que los mapas son peligrosos",
        ],
        "Que leer es una aventura",
        "📖 El texto termina: 'Luna aprendió que la verdadera aventura está en las historias que leemos.'",
        lunaPassage,
      ),
      question(
        "fallback-luna-5",
        "education",
        "EASY",
        "¿Cómo se sentía Luna al principio?",
        ["Triste", "Aburrida", "Emocionada", "Asustada"],
        "Aburrida",
        "📖 El primer párrafo dice: 'Era un día soleado y Luna estaba aburrida. No sabía qué hacer.'",
        lunaPassage,
      ),
    ],
  },
];

export const FALLBACK_CONTENT: EducationalContentItem[] = [
  {
    id: "fallback-content-solar",
    title: "🚀 Viaje por el Sistema Solar",
    description: "Conocé los 8 planetas, el Sol y otros cuerpos celestes en un recorrido animado.",
    content: LEARN_MARKDOWN_BY_TOPIC_KEY["sistema-solar"],
    contentType: "VIDEO",
    category: "astronomy",
    difficulty: "EASY",
    imageUrl: null,
    createdAt,
  },
  {
    id: "fallback-content-mariposa",
    title: "🦋 De Oruga a Mariposa: Una Transformación Increíble",
    description: "Descubrí las 4 etapas de la metamorfosis en esta lectura interactiva.",
    content: LEARN_MARKDOWN_BY_TOPIC_KEY.metamorfosis,
    contentType: "READING",
    category: "science",
    difficulty: "EASY",
    imageUrl: null,
    createdAt,
  },
  {
    id: "fallback-content-volcan",
    title: "🌋 Creá tu Propio Volcán en Casa",
    description: "Un experimento seguro y divertido para ver una erupción química.",
    content: LEARN_MARKDOWN_BY_TOPIC_KEY["volcan-casero"],
    contentType: "EXPERIMENT",
    category: "science",
    difficulty: "MEDIUM",
    imageUrl: null,
    createdAt,
  },
  {
    id: "fallback-content-egipto",
    title: "⏰ Un Día en la Vida de un Niño Egipcio",
    description: "Viajá en el tiempo y descubrí cómo vivían los niños hace 3.000 años.",
    content: LEARN_MARKDOWN_BY_TOPIC_KEY["egipto-ninos"],
    contentType: "VIDEO",
    category: "history",
    difficulty: "EASY",
    imageUrl: null,
    createdAt,
  },
  {
    id: "fallback-content-frida",
    title: "🖌️ Frida Kahlo: La Pintora que Miró al Espejo",
    description: "Conocé la historia de la artista mexicana más famosa del mundo.",
    content: LEARN_MARKDOWN_BY_TOPIC_KEY["frida-kahlo"],
    contentType: "READING",
    category: "creativity",
    difficulty: "EASY",
    imageUrl: null,
    createdAt,
  },
  {
    id: "fallback-content-mundo",
    title: "🌍 Explorá el Mundo: Mapamundi Interactivo",
    description: "Tocá cada continente y descubrí países, animales y curiosidades.",
    content: LEARN_MARKDOWN_BY_TOPIC_KEY.mapamundi,
    contentType: "INTERACTIVE",
    category: "geography",
    difficulty: "MEDIUM",
    imageUrl: null,
    createdAt,
  },
  {
    id: "fallback-content-tablas",
    title: "🎵 La Canción de las Tablas: ¡Cantá y Aprendé!",
    description: "Aprendé las tablas del 2 al 9 con melodías pegadizas.",
    content: LEARN_MARKDOWN_BY_TOPIC_KEY.tablas,
    contentType: "VIDEO",
    category: "math",
    difficulty: "EASY",
    imageUrl: null,
    createdAt,
  },
  {
    id: "fallback-content-selva",
    title: "🌿 Conocé los Animales de la Selva",
    description: "Tarjetas interactivas con fotos, sonidos y datos de 20 animales.",
    content: LEARN_MARKDOWN_BY_TOPIC_KEY.selva,
    contentType: "INTERACTIVE",
    category: "science",
    difficulty: "EASY",
    imageUrl: null,
    createdAt,
  },
];

export function findFallbackEducationalContentById(id: string): EducationalContentItem | null {
  return FALLBACK_CONTENT.find((c) => c.id === id) ?? null;
}

export function fallbackQuizzesByCategory(category?: string): FallbackQuiz[] {
  if (!category) return FALLBACK_QUIZZES;
  const normalized = category.trim().toLowerCase();
  if (normalized === "mixed") return FALLBACK_QUIZZES;
  return FALLBACK_QUIZZES.filter((quiz) => quiz.category === normalized);
}

export function fallbackQuestionsByCategory(category?: string, limit?: number): QuizQuestionItem[] {
  const rows = fallbackQuizzesByCategory(category).flatMap((quiz) => quiz.questions);
  return typeof limit === "number" ? rows.slice(0, limit) : rows;
}
