import { PrismaClient } from '../.prisma-client';

const prisma = new PrismaClient();

const demoChannels = [
  {
    slug: 'ciencia-divertida',
    name: 'Ciencia Divertida',
    description: 'Descubre el mundo con experimentos y curiosidades.',
    color: '#4CAF50',
    iconUrl: null,
  },
  {
    slug: 'maquina-tiempo',
    name: 'La Máquina del Tiempo',
    description: 'Viaja al pasado y conoce grandes civilizaciones.',
    color: '#FF9800',
    iconUrl: null,
  },
  {
    slug: 'cuentos-magicos',
    name: 'Cuentos Mágicos',
    description: 'Audiolibros y cuentos para soñar despierto.',
    color: '#9C27B0',
    iconUrl: null,
  },
  {
    slug: 'mundo-emociones',
    name: 'Mundo de Emociones',
    description: 'Aprende a entender lo que sientes.',
    color: '#E91E63',
    iconUrl: null,
  },
  {
    slug: 'habilidades-vida',
    name: 'Habilidades para la Vida',
    description: 'Todo lo que necesitas saber para crecer.',
    color: '#2196F3',
    iconUrl: null,
  },
] as const;

const demoContents = [
  {
    slug: 'dinosaurios-extincion',
    title: '¿Por qué se extinguieron los dinosaurios?',
    description: 'Descubre la teoría del meteorito y otras hipótesis fascinantes.',
    type: 'VIDEO' as const,
    category: 'SCIENCE' as const,
    ageRangeMin: 6,
    ageRangeMax: 12,
    durationSec: 240,
    thumbnailUrl: 'https://placehold.co/400x225/4CAF50/fff?text=Dinos',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    transcript: 'Hace millones de años, un meteorito cambió la Tierra para siempre.',
    tags: ['dinosaurios', 'extincion', 'espacio', 'ciencia'],
    channelSlug: 'ciencia-divertida',
  },
  {
    slug: 'egipto-faraones',
    title: 'Los secretos de los faraones',
    description: 'Viaja al antiguo Egipto y descubre cómo vivían los faraones.',
    type: 'VIDEO' as const,
    category: 'HISTORY' as const,
    ageRangeMin: 8,
    ageRangeMax: 14,
    durationSec: 300,
    thumbnailUrl: 'https://placehold.co/400x225/FF9800/fff?text=Egipto',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    transcript: 'Las pirámides guardan secretos increíbles.',
    tags: ['egipto', 'faraones', 'piramides', 'historia'],
    channelSlug: 'maquina-tiempo',
  },
  {
    slug: 'sistema-solar-planetas',
    title: 'Tour por el sistema solar',
    description: 'Un paseo por los planetas y sus lunas.',
    type: 'VIDEO' as const,
    category: 'SCIENCE' as const,
    ageRangeMin: 7,
    ageRangeMax: 13,
    durationSec: 360,
    thumbnailUrl: 'https://placehold.co/400x225/3F51B5/fff?text=Planetas',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    tags: ['planetas', 'espacio'],
    channelSlug: 'ciencia-divertida',
  },
  {
    slug: 'audiolibro-alicia',
    title: 'Alicia en el País de las Maravillas',
    description: 'Versión adaptada para niños.',
    type: 'AUDIOBOOK' as const,
    category: 'LANGUAGE' as const,
    ageRangeMin: 7,
    ageRangeMax: 12,
    durationSec: 600,
    thumbnailUrl: 'https://placehold.co/400x225/9C27B0/fff?text=Alicia',
    mediaUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    tags: ['literatura', 'fantasia'],
    channelSlug: 'cuentos-magicos',
  },
  {
    slug: 'audiolibro-peter-pan',
    title: 'Peter Pan — capítulo 1',
    description: 'Vuela a Nunca Jamás con Peter.',
    type: 'AUDIOBOOK' as const,
    category: 'LANGUAGE' as const,
    ageRangeMin: 6,
    ageRangeMax: 11,
    durationSec: 480,
    thumbnailUrl: 'https://placehold.co/400x225/7B1FA2/fff?text=Peter',
    mediaUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    tags: ['aventura'],
    channelSlug: 'cuentos-magicos',
  },
  {
    slug: 'comic-sistema-solar',
    title: 'El Sistema Solar en Cómics',
    description: 'Aprende sobre los planetas con viñetas.',
    type: 'COMIC' as const,
    category: 'SCIENCE' as const,
    ageRangeMin: 5,
    ageRangeMax: 10,
    thumbnailUrl: 'https://placehold.co/400x225/009688/fff?text=Comic',
    mediaUrl: 'https://placehold.co/800x1200/009688/fff?text=Comic+Solar',
    tags: ['comic', 'planetas'],
    channelSlug: 'ciencia-divertida',
  },
  {
    slug: 'emociones-identificar',
    title: '¿Cómo te sientes hoy?',
    description: 'Aprende a identificar y nombrar tus emociones.',
    type: 'INTERACTIVE' as const,
    category: 'EMOTIONAL_INTELLIGENCE' as const,
    ageRangeMin: 5,
    ageRangeMax: 10,
    thumbnailUrl: 'https://placehold.co/400x225/E91E63/fff?text=Emociones',
    mediaUrl: 'https://placehold.co/600x400/E91E63/fff?text=Interactivo',
    tags: ['emociones', 'empatia'],
    channelSlug: 'mundo-emociones',
  },
  {
    slug: 'dinero-ahorrar',
    title: '¿Por qué ahorrar?',
    description: 'Tu primera lección de educación financiera.',
    type: 'VIDEO' as const,
    category: 'FINANCIAL_EDUCATION' as const,
    ageRangeMin: 8,
    ageRangeMax: 14,
    durationSec: 180,
    isPremium: true,
    thumbnailUrl: 'https://placehold.co/400x225/2196F3/fff?text=Dinero',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    tags: ['dinero', 'ahorro'],
    channelSlug: 'habilidades-vida',
  },
  {
    slug: 'cuerpo-corazon',
    title: 'El corazón late',
    description: 'Cómo funciona el corazón y la circulación.',
    type: 'VIDEO' as const,
    category: 'HEALTH' as const,
    ageRangeMin: 8,
    ageRangeMax: 12,
    durationSec: 200,
    thumbnailUrl: 'https://placehold.co/400x225/F44336/fff?text=Salud',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    tags: ['cuerpo', 'salud'],
    channelSlug: 'habilidades-vida',
  },
  {
    slug: 'mapa-america',
    title: 'Mapa de América',
    description: 'Países, capitales y curiosidades.',
    type: 'ARTICLE' as const,
    category: 'GEOGRAPHY' as const,
    ageRangeMin: 9,
    ageRangeMax: 14,
    thumbnailUrl: 'https://placehold.co/400x225/8BC34A/fff?text=Mapa',
    mediaUrl: 'https://placehold.co/800x600/8BC34A/fff?text=America',
    transcript: 'América es un continente enorme con muchos países.',
    tags: ['geografia', 'mapas'],
    channelSlug: 'maquina-tiempo',
  },
  {
    slug: 'fracciones-facil',
    title: 'Fracciones fáciles',
    description: 'Divide pizzas y entiende las fracciones.',
    type: 'VIDEO' as const,
    category: 'MATH' as const,
    ageRangeMin: 8,
    ageRangeMax: 12,
    durationSec: 220,
    thumbnailUrl: 'https://placehold.co/400x225/673AB7/fff?text=Math',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    tags: ['matematicas', 'fracciones'],
    channelSlug: 'ciencia-divertida',
  },
  {
    slug: 'musica-ritmo',
    title: 'Siente el ritmo',
    description: 'Introducción al pulso y la música.',
    type: 'INTERACTIVE' as const,
    category: 'MUSIC' as const,
    ageRangeMin: 6,
    ageRangeMax: 11,
    thumbnailUrl: 'https://placehold.co/400x225/FF5722/fff?text=Musica',
    mediaUrl: 'https://placehold.co/600x400/FF5722/fff?text=Ritmo',
    tags: ['musica', 'ritmo'],
    channelSlug: 'cuentos-magicos',
  },
  {
    slug: 'naturaleza-bosque',
    title: 'Un día en el bosque',
    description: 'Animales y plantas de un ecosistema.',
    type: 'VIDEO' as const,
    category: 'NATURE' as const,
    ageRangeMin: 5,
    ageRangeMax: 10,
    durationSec: 260,
    thumbnailUrl: 'https://placehold.co/400x225/388E3C/fff?text=Bosque',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tags: ['naturaleza', 'animales'],
    channelSlug: 'ciencia-divertida',
  },
  {
    slug: 'arte-colores',
    title: 'Mezcla de colores',
    description: 'Pintura y teoría del color para niños.',
    type: 'VIDEO' as const,
    category: 'ART' as const,
    ageRangeMin: 6,
    ageRangeMax: 12,
    durationSec: 190,
    thumbnailUrl: 'https://placehold.co/400x225/E040FB/fff?text=Arte',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    tags: ['arte', 'colores'],
    channelSlug: 'mundo-emociones',
  },
  {
    slug: 'tecnologia-robots',
    title: '¿Qué es un robot?',
    description: 'Introducción amigable a la robótica.',
    type: 'ARTICLE' as const,
    category: 'TECHNOLOGY' as const,
    ageRangeMin: 9,
    ageRangeMax: 14,
    thumbnailUrl: 'https://placehold.co/400x225/607D8B/fff?text=Robot',
    mediaUrl: 'https://placehold.co/800x600/607D8B/fff?text=Robots',
    tags: ['tecnologia', 'robotica'],
    channelSlug: 'habilidades-vida',
  },
  {
    slug: 'deporte-fairplay',
    title: 'Juego limpio',
    description: 'Fair play y trabajo en equipo.',
    type: 'VIDEO' as const,
    category: 'SPORTS' as const,
    ageRangeMin: 7,
    ageRangeMax: 13,
    durationSec: 210,
    thumbnailUrl: 'https://placehold.co/400x225/00BCD4/fff?text=Deporte',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    tags: ['deporte', 'equipo'],
    channelSlug: 'habilidades-vida',
  },
];

export async function seedContentLibrary(): Promise<void> {
  const channelIdBySlug = new Map<string, string>();

  for (const ch of demoChannels) {
    const row = await prisma.contentChannel.upsert({
      where: { slug: ch.slug },
      create: { ...ch, isActive: true },
      update: {
        name: ch.name,
        description: ch.description,
        color: ch.color,
        iconUrl: ch.iconUrl,
        isActive: true,
      },
    });
    channelIdBySlug.set(ch.slug, row.id);
  }

  for (const item of demoContents) {
    const channelId = channelIdBySlug.get(item.channelSlug);
    await prisma.contentLibrary.upsert({
      where: { slug: item.slug },
      create: {
        slug: item.slug,
        title: item.title,
        description: item.description,
        type: item.type,
        category: item.category,
        ageRangeMin: item.ageRangeMin,
        ageRangeMax: item.ageRangeMax,
        durationSec: item.durationSec ?? null,
        thumbnailUrl: item.thumbnailUrl,
        mediaUrl: item.mediaUrl,
        transcript: item.transcript ?? null,
        isPremium: item.isPremium ?? false,
        tags: item.tags,
        channelId,
        isActive: true,
      },
      update: {
        title: item.title,
        description: item.description,
        thumbnailUrl: item.thumbnailUrl,
        mediaUrl: item.mediaUrl,
        isActive: true,
        channelId,
      },
    });
  }

  console.log(
    `[seed-content-library] ${demoChannels.length} canales, ${demoContents.length} contenidos.`,
  );
}

if (require.main === module) {
  seedContentLibrary()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(() => prisma.$disconnect());
}
