/**
 * Datos curiosos breves: una idea por tarjeta (lectura rápida).
 * `subject` alineado con `SubjectTag` en `libraryMediaCatalog.ts`.
 */
export type CuriositySubjectTag =
  | "ciencia"
  | "historia"
  | "naturaleza"
  | "cuerpo_humano"
  | "espacio"
  | "tecnologia"
  | "culturas";

export type CuriosityFactSeed = {
  cat: string;
  fact: string;
  subject: CuriositySubjectTag;
};

/** Cada entrada genera una tarjeta `fact-{n}` en orden. */
export const CURIOSITY_FACT_SEEDS: CuriosityFactSeed[] = [
  { cat: "Cuerpo", fact: "Un adulto suele tener unos 206 huesos.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "Los bebés tienen más piezas óseas; muchas se fusionan al crecer.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "El hueso más pequeño está en el oído: el estribo.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "Las huellas digitales se forman antes del nacimiento.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "El cerebro usa bastante glucosa incluso cuando descansás.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "La mucosa protege el estómago de su propio ácido.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "Tapate el estornudo con el codo para no salpicar tanto.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "Los músculos suelen trabajar en pares: uno tira y el otro afloja.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "El hígado puede regenerarse en parte si hay tejido sano.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "Parpadear lubrica los ojos y les da micropausas.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "La sangre es roja por la hemoglobina, que lleva oxígeno.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "Sudás principalmente para enfriarte, no para “limpiar sangre mágica”.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "Dormir ayuda a fijar recuerdos y a recuperarte.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "El tímpano vibra y pasa el sonido al oído interno.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "Las costillas protegen corazón y pulmones.", subject: "cuerpo_humano" },
  { cat: "Cuerpo", fact: "El esmalte del diente no se repara solo como la piel.", subject: "cuerpo_humano" },
  { cat: "Animales", fact: "Muchos pulpos tienen tres corazones.", subject: "naturaleza" },
  { cat: "Animales", fact: "Jirafas y humanos tenemos siete vértebras en el cuello.", subject: "naturaleza" },
  { cat: "Animales", fact: "Las abejas polinizan muchísimos alimentos que comemos.", subject: "naturaleza" },
  { cat: "Animales", fact: "Los colibríes pueden batir las alas muy rápido.", subject: "naturaleza" },
  { cat: "Animales", fact: "Las ballenas son mamíferos: respiran aire.", subject: "naturaleza" },
  { cat: "Animales", fact: "Los camaleones cambian por luz, temperatura y estado de ánimo.", subject: "naturaleza" },
  { cat: "Animales", fact: "Los murciélagos se guían con ecolocalización.", subject: "naturaleza" },
  { cat: "Animales", fact: "Las hormigas siguen rastros químicos en el suelo.", subject: "naturaleza" },
  { cat: "Animales", fact: "Los pingüinos nadan mejor de lo que vuelan.", subject: "naturaleza" },
  { cat: "Animales", fact: "Los delfines se comunican con sonidos variados.", subject: "naturaleza" },
  { cat: "Animales", fact: "Muchas serpientes “leen” moléculas del aire con la lengua.", subject: "naturaleza" },
  { cat: "Animales", fact: "Los caracoles dejan baba para deslizarse con menos roce.", subject: "naturaleza" },
  { cat: "Animales", fact: "Los koalas duermen mucho: su comida aporta poca energía.", subject: "naturaleza" },
  { cat: "Animales", fact: "Las nutrias a veces duermen tomadas de las patas para no separarse.", subject: "naturaleza" },
  { cat: "Animales", fact: "La seda de araña es muy resistente para su peso.", subject: "naturaleza" },
  { cat: "Animales", fact: "La joroba del camello guarda grasa, no un tanque de agua.", subject: "naturaleza" },
  { cat: "Animales", fact: "La mariposa monarca migra distancias enormes por generaciones.", subject: "naturaleza" },
  { cat: "Plantas", fact: "La savia sube y el agua también sale por las hojas.", subject: "naturaleza" },
  { cat: "Plantas", fact: "Las semillas viajan con viento, animales o agua.", subject: "naturaleza" },
  { cat: "Plantas", fact: "Las raíces anclan la planta y buscan agua.", subject: "naturaleza" },
  { cat: "Plantas", fact: "La clorofila captura luz: por eso muchas hojas son verdes.", subject: "naturaleza" },
  { cat: "Plantas", fact: "Algunas flores se abren de día y se cierran de noche.", subject: "naturaleza" },
  { cat: "Plantas", fact: "Muchos cactus guardan agua; los pinchos son hojas modificadas.", subject: "naturaleza" },
  { cat: "Plantas", fact: "El bambú puede crecer muy rápido con buen clima y suelo.", subject: "naturaleza" },
  { cat: "Plantas", fact: "Algunas hojas se encogen al tacto, como la mimosa pudica.", subject: "naturaleza" },
  { cat: "Tierra", fact: "Casi toda el agua del planeta es salada.", subject: "ciencia" },
  { cat: "Tierra", fact: "La Tierra está levemente achatada en los polos.", subject: "ciencia" },
  { cat: "Tierra", fact: "Las placas se mueven despacio y explican sismos y volcanes.", subject: "ciencia" },
  { cat: "Tierra", fact: "El núcleo externo líquido ayuda a generar el campo magnético.", subject: "ciencia" },
  { cat: "Sonido", fact: "El sonido son vibraciones que viajan en sólidos, líquidos o gases.", subject: "ciencia" },
  { cat: "Luz", fact: "En el espacio casi vacío casi no se ven rayos de luz sueltos.", subject: "ciencia" },
  { cat: "Luz", fact: "Las gotitas en el arcoíris dispersan la luz como prismas.", subject: "ciencia" },
  { cat: "Luz", fact: "Las plantas crecen hacia la luz: es el fototropismo.", subject: "naturaleza" },
  { cat: "Hielo", fact: "El hielo flota porque ocupa más volumen que el agua líquida igual masa.", subject: "ciencia" },
  { cat: "Agua", fact: "Arriba de la montaña el agua puede hervir a menos de 100 °C.", subject: "ciencia" },
  { cat: "Imán", fact: "Los imanes atraen fuerte el hierro, no todos los metales.", subject: "ciencia" },
  { cat: "Rayos", fact: "El rayo calienta el aire rápido; la expansión suena como trueno.", subject: "ciencia" },
  { cat: "Energía", fact: "Una batería guarda energía química y la libera como electricidad.", subject: "ciencia" },
  { cat: "Mates", fact: "El uso del cero se generalizó tarde… y cambió la matemática.", subject: "ciencia" },
  { cat: "Mates", fact: "Pi aparece en círculos, ondas y hasta en probabilidades.", subject: "ciencia" },
  { cat: "Tiempo", fact: "El año bisiesto alinea el calendario con la órbita terrestre.", subject: "ciencia" },
  { cat: "Tiempo", fact: "Los husos horarios son acuerdos humanos sobre el mismo instante.", subject: "ciencia" },
  { cat: "Historia", fact: "En Egipto el papiro fue un papel valiosísimo.", subject: "historia" },
  { cat: "Historia", fact: "La imprenta multiplicó libros más rápido que a mano.", subject: "historia" },
  { cat: "Historia", fact: "Los calendarios mezclan ciclos del Sol, la Luna y reglas humanas.", subject: "historia" },
  { cat: "Historia", fact: "Los acueductos romanos llevaban agua pendiente calculada.", subject: "historia" },
  { cat: "Historia", fact: "La agricultura estable permitió pueblos más grandes.", subject: "historia" },
  { cat: "Historia", fact: "La rueda con buen eje reduce el roce al transportar cargas.", subject: "historia" },
  { cat: "Historia", fact: "La pólvora cambió defensas y estrategias militares.", subject: "historia" },
  { cat: "Cultura", fact: "Los idiomas se mezclan con comercio, migraciones y contacto.", subject: "culturas" },
  { cat: "Cultura", fact: "Antes hubo memorias gigantes oralmente: mitos canciones genealogías.", subject: "culturas" },
  { cat: "Cultura", fact: "Muchas festividades mezclan historia local y comidas típicas.", subject: "culturas" },
  { cat: "Cultura", fact: "No todos clasifican los colores igual entre idiomas distintos.", subject: "culturas" },
  { cat: "Arte", fact: "Un pigmento muestra color según qué luz refleja hacia tus ojos.", subject: "culturas" },
  { cat: "Luna", fact: "En la Luna casi no hay atmósfera: el cielo se ve negro de día.", subject: "espacio" },
  { cat: "Planetas", fact: "Un año en Neptuno dura décadas terrestres: orbita muy lejana.", subject: "espacio" },
  { cat: "Planetas", fact: "Júpiter tiene decenas de lunas: parece una mini familia orbital.", subject: "espacio" },
  { cat: "Espacio", fact: "Saturno en promedio es menos denso que el agua líquida.", subject: "espacio" },
  { cat: "Espacio", fact: "La EEI da una vuelta a la Tierra en unos 90 minutos.", subject: "espacio" },
  { cat: "Espacio", fact: "Un meteorito brillante en el cielo suele llamarse estrella fugaz.", subject: "espacio" },
  { cat: "Espacio", fact: "Marte tiene el volcán más alto conocido del sistema solar.", subject: "espacio" },
  { cat: "Espacio", fact: "Urano rota casi de costado: quizá por un choque enorme antiguo.", subject: "espacio" },
  { cat: "Espacio", fact: "La luz del Sol llega a la Tierra en unos 8 minutos.", subject: "espacio" },
  { cat: "Espacio", fact: "En Venus un día solar es más largo que su año venusiano.", subject: "espacio" },
  { cat: "Espacio", fact: "Nuestra galaxia se llama Vía Láctea y tiene incontables estrellas.", subject: "espacio" },
  { cat: "Espacio", fact: "Un eclipse lunar es la Luna entrando en la sombra de la Tierra.", subject: "espacio" },
  { cat: "Espacio", fact: "Un eclipse solar es la Luna tapando la cara del Sol (en tu zona).", subject: "espacio" },
  { cat: "Tecnología", fact: "Un código QR compacta información en cuadritos legibles.", subject: "tecnologia" },
  { cat: "Tecnología", fact: "Internet es una red de redes con protocolos compartidos.", subject: "tecnologia" },
  { cat: "Tecnología", fact: "Contraseña larga y variada suele ganarle a una palabra obvia corta.", subject: "tecnologia" },
  { cat: "Tecnología", fact: "El GPS usa tiempos de señales de muchos satélites a la vez.", subject: "tecnologia" },
  { cat: "Tecnología", fact: "Muchas redes eléctricas usan corriente alterna para transportar mejor.", subject: "tecnologia" },
  { cat: "Tecnología", fact: "Un chip puede tener miles de millones de transistores diminutos.", subject: "tecnologia" },
  { cat: "Tecnología", fact: "El Wi‑Fi envía datos por ondas de radio en bandas reservadas.", subject: "tecnologia" },
  { cat: "Tecnología", fact: "Los juegos en 3D ensamblan muchos triángulos por segundo.", subject: "tecnologia" },
  { cat: "Tecnología", fact: "Un brazo robótico en fábrica repite movimientos con precisión estable.", subject: "tecnologia" },
  { cat: "Inventos", fact: "La brújula señala el norte magnético, distinto del norte geográfico.", subject: "tecnologia" },
  { cat: "Inventos", fact: "Palanca cambia fuerza por distancia: la energía bien usada cuenta.", subject: "ciencia" },
  { cat: "Inventos", fact: "Antibióticos atacan bacterias; el resfrío común suele ser virus.", subject: "ciencia" },
  { cat: "Inventos", fact: "Vacunas entrenan al sistema inmune sin la enfermedad fuerte típica.", subject: "ciencia" },
  { cat: "Geografía", fact: "La cumbre más alta sobre el nivel del mar suele citarse Everest.", subject: "ciencia" },
  { cat: "Geografía", fact: "El Amazonas vierte enorme cantidad de agua dulce al Atlántico.", subject: "naturaleza" },
  { cat: "Geografía", fact: "La Antártida es tierra cubierta de hielo muy grueso.", subject: "ciencia" },
  { cat: "Geografía", fact: "Existen desiertos fríos, no sólo arenas calurosas.", subject: "naturaleza" },
  { cat: "Geografía", fact: "Mar Muerto muy salado: nadar suele hacer flotar más fácil.", subject: "ciencia" },
  { cat: "Océano", fact: "Plantitas marinas diminutas aportan mucho oxígeno global.", subject: "naturaleza" },
  { cat: "Océano", fact: "En el fondo oscuro algunos peces llevan luces propias.", subject: "naturaleza" },
  { cat: "Océano", fact: "Mareas: combinación principal de Luna y Sol con la órbita.", subject: "ciencia" },
  { cat: "Océano", fact: "Un arrecife es obra de criaturitas que van sumando carbonato.", subject: "naturaleza" },
  { cat: "Clima", fact: "El viento mueve aire de zonas de alta presión hacia zonas más bajas.", subject: "ciencia" },
  { cat: "Clima", fact: "Hay arco iris doble: el segundo suele estar más débil.", subject: "ciencia" },
  { cat: "Clima", fact: "El granizo se forma por capas de hielo en nubes con fuerte ascendente.", subject: "ciencia" },
  { cat: "Clima", fact: "Hay efecto invernadero natural; el problema es acelerarlo de más.", subject: "ciencia" },
  { cat: "Química", fact: "Sal de cocina es cloruro de sodio típico; el agua lo disuelve bien.", subject: "ciencia" },
  { cat: "Química", fact: "Diamante y grafito son carbono con redes atómicas distintas.", subject: "ciencia" },
  { cat: "Química", fact: "El oro es tan maleable que se hace láminas muy finísimas.", subject: "ciencia" },
  { cat: "Química", fact: "Licuar helio estable pide frío extremo: su física es muy cuántica.", subject: "ciencia" },
  { cat: "Química", fact: "El limón es ácido suave comparado con químicos industriales fuertes.", subject: "ciencia" },
  { cat: "Física", fact: "Si ignorás el aire, diferentes masas pueden caer con igual aceleración.", subject: "ciencia" },
  { cat: "Física", fact: "Espejos lisos ordenan la luz reflejada; curvos enfocan o amplían.", subject: "ciencia" },
  { cat: "Física", fact: "Ropa oscura suele absorber más sol y sentir más calor que la clara.", subject: "ciencia" },
  { cat: "Física", fact: "Calentar fuerte un imán puede hacerlo perder magnetismo útilmente.", subject: "ciencia" },
  { cat: "Colmena", fact: "Algunos hormigueros ventilan casi como chimeneas naturales.", subject: "naturaleza" },
  { cat: "Cuerpo", fact: "La nariz humidifica el aire y filtra algo de polvo al respirar.", subject: "cuerpo_humano" },
  { cat: "Animal", fact: "El perezoso tiene digestión muy lenta adaptada hojas bajas calorías.", subject: "naturaleza" },
  { cat: "Cielo", fact: "Las constelaciones son trazos humanos sobre grupos muy lejanos.", subject: "espacio" },
  { cat: "Cielo", fact: "Ver una galaxia lejana es mirar luz tardada años o siglos atrás.", subject: "espacio" },
  { cat: "Historia", fact: "Sin confianza en la institución el papel billete apenas vale símbolo pintado.", subject: "historia" },
  { cat: "Historia", fact: "Grandes navegaciones enlazaron mundos antes de internet.", subject: "historia" },
  { cat: "Historia", fact: "Relojes unificaron horarios de tren y fábrica en siglo XIX.", subject: "historia" },
  { cat: "Historia", fact: "La fotografía siglo XIX propagó retratos rápido antes costosos sólo elites.", subject: "historia" },
  { cat: "Historia", fact: "Bibliotecas públicas abrieron acceso amplio papel lectura siglo XIX XX.", subject: "historia" },
  { cat: "Historia", fact: "Sellos postales aceleraron envíos masivos y burocracia moderna siglo XIX.", subject: "historia" },
  { cat: "Historia", fact: "Ferrocarril acortó tiempo y distancia con migraciones internas grandes.", subject: "historia" },
  { cat: "Historia", fact: "Telégrafo llevaba mensajes código muy lejos antes del teléfono masivo.", subject: "historia" },
  { cat: "Tecnología", fact: "Comprimir archivos reduce tamaño sin perder detalle suficientes muchos.", subject: "tecnologia" },
  { cat: "Tecnología", fact: "La criptografía rutinaria usa matemática de claves en apps y banca.", subject: "tecnologia" },
  { cat: "Tecnología", fact: "Pantallas OLED apagan pixeles reales así el negro se ve muy profundo.", subject: "tecnologia" },
  { cat: "Ciencia", fact: "El ADN porta instrucciones químicas que las células leen.", subject: "ciencia" },
  { cat: "Ciencia", fact: "Las mitocondrias son granjas de energía dentro de tus células.", subject: "ciencia" },
  { cat: "Ciencia", fact: "Modelo simple del átomo: núcleo positivo y electrones negativos afuera.", subject: "ciencia" },
  { cat: "Ciencia", fact: "Espirales chicas tornado y grandes galaxia mismo dibujo muy distinta escala.", subject: "ciencia" },
  { cat: "Naturaleza", fact: "Micelio de hongos bajo bosque mueve nutrientes entre plantas algunos estudios.", subject: "naturaleza" },
  { cat: "Naturaleza", fact: "Coral muy caliente se blanquea estrés térmico se ve hasta satélite.", subject: "naturaleza" },
  { cat: "Naturaleza", fact: "Oso polar blanco retiene mejor calor cuerpo mismo noche larga.", subject: "naturaleza" },
];
