import { useMemo } from "react";
import { Platform, StyleSheet } from "react-native";

import { useTheme } from "../contexts/ThemeContext";
import type { AppColors } from "../theme/appTheme";
import { avatarSize, iconSize, radius, screenEdge, space, typography } from "../theme/tokens";

export function useExploreStyles() {
  const { colors } = useTheme();
  return useMemo(() => createExploreStyles(colors), [colors]);
}

export function createExploreStyles(c: AppColors) {
  return StyleSheet.create({
    list: {
      paddingHorizontal: screenEdge.horizontal,
      paddingTop: space.sm,
      paddingBottom: space.xl,
      backgroundColor: c.background,
    },
    emptyList: {
      flexGrow: 1,
      justifyContent: "center",
      padding: space.lg,
      backgroundColor: c.background,
    },
    centered: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: space.lg,
      backgroundColor: c.background,
    },
    loadingHint: {
      marginTop: space.sm + space.xs,
      fontSize: typography.bodyLarge,
      color: c.loadingText,
      fontWeight: "600",
    },
    listHeader: {
      marginBottom: space.md,
      paddingTop: space.xs,
    },
    exploreBrandRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.md,
      marginBottom: space.md,
    },
    exploreBrandTextCol: {
      flex: 1,
      minWidth: 0,
    },
    exploreBrandTitle: {
      fontSize: typography.title,
      fontWeight: "800",
      lineHeight: typography.title + 2,
      letterSpacing: -0.3,
    },
    exploreBrandTagline: {
      fontSize: typography.secondary,
      fontWeight: "700",
      marginTop: 2,
      letterSpacing: -0.2,
    },
    heroTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: space.sm,
      marginBottom: space.sm,
    },
    heroTitleActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.xs + space.xs,
    },
    heroTitle: {
      fontSize: typography.title,
      fontWeight: "900",
      color: c.exploreHeroTitle,
      letterSpacing: -0.8,
    },
    heroSubtitle: {
      fontSize: typography.bodyLarge,
      color: c.exploreHeroSubtitle,
      fontWeight: "600",
      lineHeight: typography.bodyLarge + space.sm,
      opacity: 0.95,
    },
    continueSection: {
      marginBottom: space.md,
      paddingVertical: space.sm + space.xs,
      paddingHorizontal: space.sm,
      borderRadius: radius.cardSm,
      borderWidth: 1,
      borderColor: c.borderSubtle,
      backgroundColor: c.mode === "dark" ? c.cardElevated : "#f8fafc",
    },
    continueSectionTitle: {
      fontSize: typography.bodyLarge + 1,
      fontWeight: "800",
      color: c.text,
      marginBottom: space.xs - 2,
    },
    continueSectionHint: {
      fontSize: typography.secondary,
      color: c.textMuted,
      fontWeight: "600",
      marginBottom: space.sm,
    },
    continueCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
      padding: space.sm,
      borderRadius: radius.cardSm - 2,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
    },
    continueCardSecond: {
      marginTop: space.sm,
    },
    continueCardPressed: {
      opacity: 0.92,
      transform: [{ scale: 0.99 }],
    },
    continueCardDisabled: {
      opacity: 0.55,
    },
    continueCardIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.mode === "dark" ? c.primarySoft : c.primarySoft,
    },
    continueCardTextCol: {
      flex: 1,
      minWidth: 0,
    },
    continueCardKicker: {
      fontSize: typography.secondary - 1,
      fontWeight: "700",
      color: c.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.4,
      marginBottom: 2,
    },
    continueCardTitle: {
      fontSize: typography.body,
      fontWeight: "800",
      color: c.text,
      lineHeight: typography.body + space.xs,
    },
    continueCardCta: {
      marginTop: space.xs,
      fontSize: typography.secondary,
      fontWeight: "800",
      color: c.link,
    },
    continueInfoRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: space.sm,
      marginBottom: space.sm,
    },
    continueInfoRowSecond: {
      marginTop: space.xs,
    },
    continueRowLabel: {
      fontSize: typography.secondary - 1,
      fontWeight: "700",
      color: c.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.4,
      marginBottom: 4,
    },
    continueRowValue: {
      fontSize: typography.body,
      fontWeight: "800",
      color: c.text,
      lineHeight: typography.body + space.xs,
    },
    continueMainButton: {
      marginTop: space.sm,
      paddingVertical: space.md - space.xs,
      paddingHorizontal: space.md,
      borderRadius: radius.cardSm,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    continueMainButtonPressed: {
      opacity: 0.92,
      transform: [{ scale: 0.99 }],
    },
    continueMainButtonDisabled: {
      opacity: 0.55,
    },
    continueMainButtonText: {
      fontSize: typography.bodyLarge,
      fontWeight: "800",
      color: c.textOnPrimary,
    },
    inlineErr: {
      marginTop: space.sm + space.xs,
      color: c.error,
      fontWeight: "600",
    },
    recForYouSection: {
      marginBottom: space.md,
      padding: space.md,
      borderRadius: radius.sheet,
      borderWidth: 1,
      borderColor: c.recWrapBorder,
      backgroundColor: c.recWrapBg,
    },
    recForYouTitle: {
      fontSize: typography.bodyLarge + 2,
      fontWeight: "800",
      color: c.recTitle,
      marginBottom: space.xs - 2,
    },
    recForYouSubtitle: {
      fontSize: typography.secondary,
      fontWeight: "600",
      color: c.recSubtitle,
      marginBottom: space.sm,
    },
    recForYouBlockRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
      marginBottom: space.sm,
    },
    recForYouBlockLabel: {
      fontSize: typography.secondary,
      fontWeight: "800",
      color: c.recBlockLabel,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    recForYouScroll: {
      gap: space.sm,
      paddingBottom: space.xs,
    },
    recForYouGameCard: {
      minWidth: 200,
      maxWidth: 240,
      borderRadius: radius.cardSm,
      borderWidth: 1,
      borderColor: c.recGameChipBorder,
      backgroundColor: c.recGameChipBg,
      padding: space.sm,
    },
    recForYouGameTitle: {
      fontSize: typography.body,
      fontWeight: "800",
      color: c.recGameName,
      marginBottom: space.xs,
    },
    recForYouGameMeta: {
      fontSize: typography.secondary,
      color: c.recGameMeta,
      fontWeight: "600",
    },
    recForYouLearnCard: {
      minWidth: 200,
      maxWidth: 240,
      borderRadius: radius.cardSm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderSubtle,
      backgroundColor: c.card,
      padding: space.sm,
    },
    recForYouLearnTitle: {
      fontSize: typography.body,
      fontWeight: "800",
      color: c.text,
      marginBottom: space.xs,
    },
    recForYouLearnMeta: {
      fontSize: typography.secondary,
      color: c.textMuted,
      fontWeight: "600",
    },
    recForYouMixedBadge: {
      alignSelf: "flex-start",
      marginBottom: space.xs,
      paddingHorizontal: space.sm,
      paddingVertical: 2,
      borderRadius: 999,
      backgroundColor: c.primarySoft,
      borderWidth: 1,
      borderColor: c.primarySoftBorder,
    },
    recForYouMixedBadgeText: {
      fontSize: typography.secondary - 2,
      fontWeight: "800",
      color: c.primaryStrong,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    recForYouMixedThumb: {
      width: "100%",
      height: 72,
      borderRadius: radius.cardSm - 4,
      marginBottom: space.xs,
      backgroundColor: c.borderSubtle,
    },
    learnSection: {
      marginTop: space.md,
      marginBottom: space.md,
    },
    gamesSection: {
      marginTop: space.md,
      marginBottom: space.md,
    },
    gamesSectionTitle: {
      fontSize: typography.bodyLarge + 2,
      fontWeight: "800",
      color: c.text,
      marginBottom: space.xs,
    },
    gamesDifficultyHint: {
      fontSize: typography.secondary,
      color: c.textMuted,
      fontWeight: "600",
      marginBottom: space.sm,
      lineHeight: 18,
    },
    gamesCardsRow: {
      gap: space.sm,
    },
    gameCard: {
      minWidth: 210,
      maxWidth: 260,
      borderRadius: radius.cardSm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderSubtle,
      backgroundColor: c.card,
      padding: space.sm,
    },
    gameCardPressed: {
      transform: [{ scale: 0.98 }],
    },
    gameCardTitle: {
      color: c.text,
      fontSize: typography.bodyLarge,
      fontWeight: "700",
      marginBottom: space.xs,
    },
    gameCardMeta: {
      color: c.textMuted,
      fontSize: typography.secondary,
      fontWeight: "600",
    },
    gameDifficultyRow: {
      marginTop: space.sm,
      flexDirection: "row",
      gap: space.xs,
    },
    gameDifficultyChip: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: c.borderSubtle,
      backgroundColor: c.cardElevated,
      paddingHorizontal: space.sm,
      paddingVertical: space.xs,
    },
    gameDifficultyChipPressed: {
      transform: [{ scale: 0.97 }],
    },
    gameDifficultyChipText: {
      color: c.text,
      fontSize: typography.secondary,
      fontWeight: "700",
    },
    gameDifficultyChipRecommended: {
      borderColor: c.primary,
      borderWidth: 2,
      backgroundColor: c.primarySoft,
    },
    gameDifficultyChipTextRecommended: {
      color: c.primary,
      fontWeight: "800",
    },
    learnSectionTitle: {
      fontSize: typography.bodyLarge + 2,
      fontWeight: "800",
      color: c.text,
      marginBottom: space.sm,
    },
    learnCardsRow: {
      gap: space.sm,
    },
    quizCtaBtn: {
      marginTop: space.sm,
      marginBottom: space.sm,
      borderRadius: radius.cardSm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderSubtle,
      backgroundColor: c.cardElevated,
      paddingHorizontal: space.md,
      paddingVertical: space.sm,
      alignSelf: "flex-start",
    },
    quizCtaBtnPressed: {
      transform: [{ scale: 0.98 }],
    },
    quizCtaText: {
      color: c.text,
      fontSize: typography.body,
      fontWeight: "800",
    },
    learnCard: {
      minWidth: 210,
      maxWidth: 260,
      borderRadius: radius.cardSm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderSubtle,
      backgroundColor: c.card,
      padding: space.sm,
    },
    learnCardPressed: {
      transform: [{ scale: 0.98 }],
    },
    learnCardTitle: {
      color: c.text,
      fontSize: typography.bodyLarge,
      fontWeight: "700",
      marginBottom: space.xs,
    },
    learnCardMeta: {
      color: c.textMuted,
      fontSize: typography.secondary,
      fontWeight: "600",
    },
    emptyText: {
      textAlign: "center",
      color: c.emptyText,
      fontSize: typography.bodyLarge,
      paddingVertical: space.xl,
    },
    errorText: {
      color: c.error,
      textAlign: "center",
      fontSize: typography.bodyLarge,
    },
    /** Entre tarjetas de explorar (línea fina; ver `ItemSeparatorComponent`). */
    postSeparator: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: c.borderSubtle,
      marginVertical: space.sm,
      opacity: 0.75,
    },
    exploreCard: {
      marginBottom: 0,
      backgroundColor: c.card,
      borderRadius: radius.card,
      borderLeftWidth: 4,
      overflow: "hidden",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderSubtle,
      ...Platform.select({
        ios: {
          shadowColor: c.shadow,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.12,
          shadowRadius: 12,
        },
        android: { elevation: 4 },
        default: {
          shadowColor: c.shadow,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.1,
          shadowRadius: 10,
        },
      }),
    },
    exploreCardPressed: {
      transform: [{ scale: 0.98 }],
    },
    exploreCardInner: {
      paddingVertical: space.xs + space.xs,
      paddingHorizontal: space.sm + space.xs,
    },
    exploreCardHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
      marginBottom: space.xs,
    },
    exploreAvatarOuter: {
      overflow: "hidden",
      backgroundColor: c.avatarBg,
    },
    exploreAvatarImg: {
      backgroundColor: c.avatarBg,
    },
    exploreAvatarPh: {
      borderWidth: 2,
      backgroundColor: c.cardElevated,
      alignItems: "center",
      justifyContent: "center",
    },
    exploreAvatarPhText: {
      fontWeight: "900",
      color: c.avatarPhText,
    },
    exploreHeaderTextCol: {
      flex: 1,
      minWidth: 0,
    },
    exploreTypeAndCategoryRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: space.xs + 2,
      marginTop: space.xs,
    },
    exploreNameTimeRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "nowrap",
      flexShrink: 1,
      minWidth: 0,
      gap: 0,
    },
    exploreUsername: {
      fontSize: 14,
      lineHeight: 18,
      fontWeight: "700",
      color: c.text,
      flexShrink: 1,
    },
    exploreTimeSep: {
      fontSize: 12,
      color: c.textMuted,
      fontWeight: "400",
    },
    exploreTimeMeta: {
      fontSize: 12,
      color: c.textMuted,
      fontWeight: "400",
      flexShrink: 0,
    },
    exploreContent: {
      fontSize: 15,
      lineHeight: 21,
      color: c.exploreContent,
      marginTop: 6,
      marginBottom: 0,
    },
    explorePostImage: {
      width: "100%",
      height: space.md * 10 + space.sm,
      borderRadius: radius.cardSm,
      marginTop: 6,
      marginBottom: 4,
      backgroundColor: c.avatarBg,
    },
    exploreBadgeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
      marginTop: 4,
      marginBottom: 0,
    },
    exploreBadgeIconWrap: {
      width: iconSize.md + space.md + space.xs,
      height: iconSize.md + space.md + space.xs,
      borderRadius: space.sm,
      borderWidth: 2,
      backgroundColor: c.card,
      alignItems: "center",
      justifyContent: "center",
    },
    exploreBadgeIcon: {
      fontSize: iconSize.md,
      lineHeight: iconSize.md + space.xs,
    },
    exploreRarityPill: {
      borderWidth: 1,
      borderRadius: space.sm,
      paddingHorizontal: space.sm,
      paddingVertical: space.xs,
    },
    exploreRarityText: {
      fontSize: typography.secondary,
      fontWeight: "800",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    exploreFooter: {
      marginTop: 4,
      paddingTop: 0,
      borderTopWidth: 0,
    },
    footerLoad: {
      paddingVertical: space.md + space.sm,
      alignItems: "center",
      gap: space.sm,
    },
    footerLoadText: {
      fontSize: typography.body - 1,
      color: c.footerMuted,
      fontWeight: "600",
    },
    footerEndText: {
      textAlign: "center",
      fontSize: typography.body - 1,
      color: c.footerMuted,
      fontWeight: "600",
      paddingVertical: space.md + space.sm,
    },
  });
}
