import { useMemo } from "react";
import { Platform, StyleSheet } from "react-native";

import { useTheme } from "../contexts/ThemeContext";
import type { AppColors } from "../theme/appTheme";
import { avatarSize, iconSize, radius, screenEdge, space, typography } from "../theme/tokens";

export function useFeedStyles() {
  const { colors } = useTheme();
  return useMemo(() => createFeedStyles(colors), [colors]);
}

export function createFeedStyles(c: AppColors) {
  return StyleSheet.create({
    list: {
      paddingHorizontal: screenEdge.horizontal,
      paddingTop: space.md,
      paddingBottom: space.xl + space.sm,
      backgroundColor: c.background,
    },
    emptyList: {
      flexGrow: 1,
      justifyContent: "center",
      padding: space.lg,
      backgroundColor: c.background,
    },
    centered: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: space.lg,
      gap: space.md,
      backgroundColor: c.background,
    },
    loadingHint: {
      marginTop: space.sm + space.xs,
      fontSize: typography.bodyLarge,
      color: c.loadingText,
    },
    listHeader: {
      marginBottom: space.xs,
    },
    recommendedSectionOuter: {
      marginBottom: space.xs,
    },
    recommendedSectionHighlightActive: {
      padding: space.xs + space.xs - 2,
      marginHorizontal: -space.xs / 2,
      marginBottom: space.sm,
      borderRadius: 22,
      borderWidth: 3,
      borderColor: c.highlightRingBorder,
      backgroundColor: c.highlightRingBg,
      ...Platform.select({
        ios: {
          shadowColor: c.recWrapBorder,
          shadowOffset: { width: 0, height: 0 },
          shadowOpacity: 0.35,
          shadowRadius: 12,
        },
        android: { elevation: 8 },
        default: {},
      }),
    },
    friendsEmptyBanner: {
      marginBottom: space.sm + space.xs,
      paddingVertical: space.md - space.xs,
      paddingHorizontal: space.md - space.xs,
      borderRadius: radius.cardSm,
      backgroundColor: c.friendsBannerBg,
      borderWidth: 1,
      borderColor: c.friendsBannerBorder,
    },
    friendsEmptyText: {
      fontSize: typography.bodyLarge,
      fontWeight: "600",
      color: c.friendsBannerText,
      textAlign: "center",
      lineHeight: 22,
    },
    inactivityReminderBanner: {
      marginBottom: space.sm + space.xs,
      paddingVertical: space.md - space.xs,
      paddingHorizontal: space.md - space.xs,
      borderRadius: radius.cardSm,
      backgroundColor: c.primarySoft,
      borderWidth: 1,
      borderColor: c.primarySoftBorder,
    },
    inactivityReminderText: {
      fontSize: typography.bodyLarge,
      fontWeight: "600",
      color: c.primaryStrong,
      textAlign: "center",
      lineHeight: 22,
    },
    recommendedWrap: {
      marginBottom: space.md,
      borderRadius: radius.sheet,
      overflow: "hidden",
      borderWidth: 2,
      borderColor: c.recWrapBorder,
      backgroundColor: c.recWrapBg,
      ...Platform.select({
        ios: {
          shadowColor: c.recWrapBorder,
          shadowOffset: { width: 0, height: 6 },
          shadowOpacity: 0.18,
          shadowRadius: 14,
        },
        android: { elevation: 6 },
        default: {},
      }),
    },
    recommendedGlow: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.recGlow,
    },
    recommendedInner: {
      paddingHorizontal: space.md,
      paddingVertical: space.sm,
    },
    recommendedLoadingBox: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm + space.xs,
      paddingVertical: space.md,
      paddingHorizontal: space.md - space.xs,
    },
    recommendedLoadingText: {
      fontSize: typography.body,
      fontWeight: "600",
      color: c.recGameMeta,
    },
    recommendedTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
      marginBottom: space.sm + space.xs,
    },
    recommendedTitleTextCol: {
      flex: 1,
      minWidth: 0,
    },
    recommendedTitle: {
      fontSize: typography.title,
      fontWeight: "900",
      color: c.recTitle,
      letterSpacing: -0.3,
    },
    recommendedSubtitle: {
      marginTop: space.xs / 2,
      fontSize: typography.body,
      fontWeight: "600",
      color: c.recSubtitle,
      opacity: 0.9,
    },
    recommendedBlockLabel: {
      fontSize: typography.secondary,
      fontWeight: "800",
      color: c.recBlockLabel,
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: space.sm,
    },
    recommendedBlockSpacer: {
      marginTop: space.md,
    },
    recGamesScrollContent: {
      paddingRight: space.sm,
      paddingBottom: space.xs,
      gap: space.sm + space.xs,
      flexDirection: "row",
    },
    recHorizontalScrollTrack: {
      marginTop: space.sm,
      height: 4,
      borderRadius: 2,
      overflow: "hidden",
      backgroundColor: c.borderSubtle,
    },
    recGameChip: {
      width: 248,
      paddingVertical: 0,
      paddingHorizontal: 0,
      marginRight: 0,
      borderRadius: radius.cardSm,
      backgroundColor: "transparent",
      borderWidth: 0,
      borderColor: "transparent",
    },
    recGameChipReadOnly: {
      opacity: 0.55,
      borderColor: c.recGameReadOnlyBorder,
      backgroundColor: c.recGameReadOnlyBg,
    },
    recGameChipReadOnlyPressed: {
      opacity: 0.62,
    },
    recGameName: {
      fontSize: typography.bodyLarge,
      fontWeight: "800",
      color: c.recGameName,
      marginBottom: space.xs + space.xs - 2,
    },
    recGameMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.xs,
      marginTop: space.xs,
    },
    recGameMeta: {
      flex: 1,
      fontSize: typography.secondary,
      fontWeight: "600",
      color: c.recGameMeta,
    },
    recPostCard: {
      marginBottom: space.sm,
      borderRadius: radius.card,
      backgroundColor: c.recPostCardBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.recPostCardBorder,
      paddingVertical: space.md,
      paddingHorizontal: space.md,
      ...Platform.select({
        ios: {
          shadowColor: c.shadow,
          shadowOffset: { width: 0, height: 3 },
          shadowOpacity: 0.12,
          shadowRadius: 12,
        },
        android: { elevation: 4 },
        default: {
          shadowColor: c.shadow,
          shadowOffset: { width: 0, height: 3 },
          shadowOpacity: 0.1,
          shadowRadius: 10,
        },
      }),
    },
    recPostBody: {
      marginTop: 6,
    },
    recPostContent: {
      fontSize: 15,
      lineHeight: 21,
      color: c.recPostContent,
      marginBottom: 0,
    },
    recPostFooter: {
      marginTop: 4,
      paddingTop: 0,
      borderTopWidth: 0,
    },
    fetchingBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm + space.xs,
      paddingVertical: space.sm + space.xs,
      paddingHorizontal: space.sm + space.xs,
      backgroundColor: c.fetchingBannerBg,
      borderRadius: space.sm + space.xs,
      marginBottom: space.sm + space.xs,
      borderWidth: 1,
      borderColor: c.fetchingBannerBorder,
    },
    fetchingBannerText: {
      fontSize: typography.body,
      color: c.fetchingBannerText,
      fontWeight: "600",
    },
    inlineErrorBanner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: space.sm + space.xs,
      padding: space.sm + space.xs,
      backgroundColor: c.errorSoft,
      borderRadius: space.sm + space.xs,
      marginBottom: space.sm + space.xs,
      borderWidth: 1,
      borderColor: c.errorBorder,
    },
    inlineErrorText: {
      flex: 1,
      fontSize: typography.body,
      color: c.error,
    },
    inlineErrorDismiss: {
      fontSize: typography.body,
      fontWeight: "700",
      color: c.link,
    },
    /** Separador entre filas del feed (línea fina + aire; ver `ItemSeparatorComponent`). */
    postSeparator: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: c.borderSubtle,
      marginVertical: space.md,
      maxWidth: 560,
      width: "100%",
      alignSelf: "center",
      opacity: 0.85,
    },
    /** Ancho máximo del post (sensación de columna centrada en pantallas anchas). */
    card: {
      width: "100%",
      maxWidth: 560,
      alignSelf: "center",
      marginBottom: 0,
    },
    /** Feedback al tocar la tarjeta (feed / recomendados). */
    cardPressed: {
      transform: [{ scale: 0.98 }],
    },
    cardInner: {
      backgroundColor: c.card,
      borderRadius: radius.card,
      padding: space.md,
      borderWidth: 1,
      borderColor: c.borderSubtle,
      ...Platform.select({
        ios: {
          shadowColor: c.shadow,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.14,
          shadowRadius: 14,
        },
        android: { elevation: 5 },
        default: {
          shadowColor: c.shadow,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.12,
          shadowRadius: 12,
        },
      }),
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
      marginBottom: space.xs,
    },
    /** Avatar post: circular (`avatarSize.feedCompact`). */
    avatarOuterCompact: {
      width: avatarSize.feedCompact,
      height: avatarSize.feedCompact,
      borderRadius: avatarSize.feedCompact / 2,
      overflow: "hidden",
      backgroundColor: c.avatarBg,
    },
    avatarImageCompact: {
      width: avatarSize.feedCompact,
      height: avatarSize.feedCompact,
      borderRadius: avatarSize.feedCompact / 2,
    },
    avatarPlaceholderCompact: {
      width: avatarSize.feedCompact,
      height: avatarSize.feedCompact,
      borderRadius: avatarSize.feedCompact / 2,
      backgroundColor: c.avatarPh,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarPlaceholderTextCompact: {
      fontSize: 11,
      fontWeight: "800",
      color: c.avatarPhText,
    },
    avatarEmojiCompact: {
      fontSize: Math.round(avatarSize.feedCompact * 0.5),
      textAlign: "center",
      lineHeight: Math.round(avatarSize.feedCompact * 0.55),
    },
    /** Usuario y hora en una sola línea (avatar a la izquierda). */
    nameTimeRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "nowrap",
      flexShrink: 1,
      minWidth: 0,
      gap: 0,
    },
    username: {
      fontWeight: "700",
      fontSize: 14,
      lineHeight: 18,
      color: c.text,
      flexShrink: 1,
    },
    timeSeparator: {
      fontSize: 12,
      color: c.textMuted,
      fontWeight: "400",
    },
    timeMeta: {
      fontSize: 12,
      color: c.textMuted,
      fontWeight: "400",
      flexShrink: 0,
    },
    cardHeaderTextCol: {
      flex: 1,
      minWidth: 0,
    },
    /** Tipo (🎮/📚/🏆) + chip de categoría temática. */
    feedTypeAndCategoryRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: space.xs + 2,
      marginTop: space.xs,
    },
    categoryFilterTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
      marginBottom: space.sm + space.xs,
      marginTop: space.sm,
    },
    categoryFilterTitle: {
      fontSize: typography.secondary,
      fontWeight: "800",
      color: c.categoryFilterTitle,
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    categoryFilterScroll: {
      flexDirection: "row",
      alignItems: "center",
      paddingBottom: space.sm + space.xs,
      paddingRight: space.sm,
    },
    categoryFilterChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.xs + space.xs - 2,
      paddingHorizontal: space.md - space.xs,
      paddingVertical: space.sm + space.xs,
      marginRight: space.sm,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: c.chipBorder,
      backgroundColor: c.chipBg,
    },
    categoryFilterChipActive: {
      backgroundColor: c.chipActiveBg,
      borderColor: c.chipActiveBorder,
      borderWidth: 2,
    },
    categoryFilterChipPressed: {
      opacity: 0.88,
    },
    categoryFilterChipReadOnly: {
      opacity: 0.5,
    },
    categoryFilterChipText: {
      fontSize: typography.body - 1,
      fontWeight: "600",
      color: c.chipText,
      maxWidth: 140,
    },
    categoryFilterChipTextActive: {
      color: c.chipTextActive,
      fontWeight: "800",
    },
    cardBody: {
      marginTop: space.sm,
      marginBottom: 0,
    },
    content: {
      fontSize: 15,
      lineHeight: 21,
      color: c.textBody,
      marginBottom: 0,
    },
    badgeBlock: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
      marginTop: 4,
      marginBottom: 0,
    },
    badgeIconWrap: {
      width: iconSize.md + space.md + space.xs,
      height: iconSize.md + space.md + space.xs,
      borderRadius: space.sm,
      backgroundColor: c.card,
      borderWidth: 2,
      borderColor: c.badgeIconBorder,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    badgeIcon: {
      fontSize: iconSize.md,
      lineHeight: iconSize.md + space.xs,
    },
    rarityPill: {
      borderWidth: 1,
      borderRadius: space.sm,
      paddingHorizontal: space.sm,
      paddingVertical: space.xs,
    },
    rarityText: {
      fontSize: typography.secondary,
      fontWeight: "800",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    cardFooter: {
      marginTop: space.sm,
      paddingTop: space.xs,
      borderTopWidth: 0,
    },
    emptyText: {
      textAlign: "center",
      color: c.emptyText,
      fontSize: typography.bodyLarge,
    },
    errorText: {
      color: c.error,
      textAlign: "center",
      fontSize: typography.bodyLarge,
      lineHeight: typography.bodyLarge + space.sm,
    },
    mono: {
      fontFamily: "monospace",
      fontSize: typography.body - 1,
    },
    retryBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: space.sm,
      marginTop: space.sm,
      backgroundColor: c.primary,
      borderRadius: space.sm + space.xs,
      paddingVertical: space.md - space.xs,
      paddingHorizontal: space.md + space.xs,
    },
    retryBtnText: {
      color: c.textOnPrimary,
      fontWeight: "700",
      fontSize: typography.bodyLarge,
    },
    createPostBtn: {
      backgroundColor: c.primary,
      paddingVertical: space.md - space.xs,
      paddingHorizontal: space.md + space.sm,
      borderRadius: radius.cardSm,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: space.md + space.xs,
    },
    createPostBtnPressed: {
      opacity: 0.9,
    },
    createPostBtnDisabled: {
      opacity: 0.85,
    },
    createPostBtnInner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: space.sm + 2,
    },
    createPostBtnText: {
      color: c.textOnPrimary,
      fontSize: typography.bodyLarge,
      fontWeight: "700",
    },
    modalRoot: {
      flex: 1,
      backgroundColor: c.modalOverlay,
    },
    modalDismissArea: {
      flex: 1,
    },
    modalKb: {
      width: "100%",
    },
    modalCard: {
      backgroundColor: c.modalCard,
      borderTopLeftRadius: space.md,
      borderTopRightRadius: space.md,
      padding: space.md + space.sm,
      paddingBottom: space.md + space.md - space.xs,
      maxHeight: "85%",
    },
    modalTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
      marginBottom: space.sm,
    },
    modalTitle: {
      fontSize: typography.title + 2,
      fontWeight: "800",
      color: c.text,
    },
    modalSubtitle: {
      fontSize: typography.body,
      color: c.textMuted,
      lineHeight: typography.body + space.sm,
      marginBottom: space.md,
    },
    modalInput: {
      borderWidth: 1,
      borderColor: c.inputBorder,
      borderRadius: space.sm + space.xs,
      padding: space.md - space.xs,
      fontSize: typography.bodyLarge,
      color: c.inputText,
      minHeight: 140,
      marginBottom: space.sm,
    },
    modalCounterRow: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginBottom: space.md,
    },
    modalInlineError: {
      borderWidth: 1,
      borderColor: c.errorBorder,
      backgroundColor: c.errorSoft,
      borderRadius: space.sm + space.xs,
      padding: space.sm + space.xs,
      marginBottom: space.sm + space.xs,
      gap: space.sm,
    },
    modalInlineErrorText: {
      fontSize: typography.body,
      lineHeight: typography.body + space.sm,
      color: c.error,
      fontWeight: "600",
    },
    modalInlineRetryBtn: {
      alignSelf: "flex-start",
      backgroundColor: c.primary,
      borderRadius: space.sm,
      paddingVertical: space.sm,
      paddingHorizontal: space.sm + space.xs,
    },
    modalInlineRetryPressed: {
      opacity: 0.9,
    },
    modalInlineRetryText: {
      color: c.textOnPrimary,
      fontSize: typography.body - 1,
      fontWeight: "700",
    },
    modalCounter: {
      fontSize: typography.secondary,
      fontWeight: "600",
      color: c.textSecondary,
    },
    modalCounterFull: {
      color: c.error,
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      gap: space.sm + space.xs,
    },
    modalBtn: {
      paddingVertical: space.sm + space.xs,
      paddingHorizontal: space.md + space.xs,
      borderRadius: space.sm + space.xs,
      minWidth: 112,
      alignItems: "center",
      justifyContent: "center",
    },
    modalBtnLoadingRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
    },
    modalBtnGhost: {
      backgroundColor: c.ghostBg,
    },
    modalBtnGhostText: {
      fontSize: typography.bodyLarge,
      fontWeight: "600",
      color: c.ghostText,
    },
    modalBtnPrimary: {
      backgroundColor: c.primary,
    },
    modalBtnDisabled: {
      opacity: 0.6,
    },
    modalBtnPrimaryText: {
      fontSize: typography.bodyLarge,
      fontWeight: "700",
      color: c.textOnPrimary,
    },
  });
}
